import { Injectable } from '@nestjs/common';

import { type GitHubStatusProvider, type GitHubStatusSummary } from '~server/github/github-status.provider';

/**
 * Mock implementation of the GitHub status provider used during development.
 * Returns a fixed, GitHub-like summary payload.
 */
@Injectable()
export class MockGitHubStatusProvider implements GitHubStatusProvider {
  async getSummary(): Promise<GitHubStatusSummary> {
    const now = new Date().toISOString();

    return {
      page: {
        id: this.generateRandomId(),
        name: 'GitHub',
        url: 'https://www.githubstatus.com',
        time_zone: 'Etc/UTC',
        updated_at: now,
      },
      components: [
        {
          id: this.generateRandomId(),
          name: 'Git Operations',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 1,
          description: 'Performance of git clones, pulls, pushes, and associated operations',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Webhooks',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 2,
          description: 'Real time HTTP callbacks of user-generated and system events',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Visit www.githubstatus.com for more information',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 3,
          description: this.generateRandomId(),
          showcase: false,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'API Requests',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 4,
          description: 'Requests for GitHub APIs',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Issues',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 5,
          description: 'Requests for Issues on GitHub.com',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Pull Requests',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 6,
          description: 'Requests for Pull Requests on GitHub.com',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Actions',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 7,
          description: 'Workflows, Compute and Orchestration for GitHub Actions',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Packages',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 8,
          description: 'API requests and webhook delivery for GitHub Packages',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Pages',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 9,
          description: 'Frontend application and API servers for Pages builds',
          showcase: true,
          start_date: this.generateRandomId(),
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Codespaces',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 10,
          description: 'Orchestration and Compute for GitHub Codespaces',
          showcase: true,
          start_date: '2021-08-11',
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
        {
          id: this.generateRandomId(),
          name: 'Copilot',
          status: 'operational',
          created_at: now,
          updated_at: now,
          position: 11,
          description: this.generateRandomId(),
          showcase: true,
          start_date: '2022-06-21',
          group_id: this.generateRandomId(),
          page_id: this.generateRandomId(),
          group: false,
          only_show_if_degraded: false,
        },
      ],
      incidents: [],
      scheduled_maintenances: [],
      status: {
        indicator: 'none',
        description: 'All Systems Operational',
      },
    } as const;
  }

  private generateRandomId() {
    return Math.random().toString(36).substring(2, 14);
  }
}
